version: "3"
services:
  web:
    build: .
    container_name: semi-automatic-pancake
    volumes:
      - .:/code
      - static:/code/static_cdn
      - media:/code/media_cdn
    depends_on:
      - db
    expose:
      - 8080
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 server.wsgi -b 0.0.0.0:8080"

  db:
    image: postgres
    restart: unless-stopped
    expose:
      - "5432"


  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./logs/:/code/logs
      - static:/code/static_cdn
      - media:/code/media_cdn
    ports:
      - "1221:80"
    links:
      - web
volumes:
  pgdata:
  media:
  static:
